spring.application.name=splitwise

# Database Configuration
spring.datasource.url=jdbc:${SPRING_DATASOURCE_URL:postgresql://localhost:5432/splitwise23}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:split_api_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:15886}
# Modern Spring Boot often auto-detects the driver, but keeping it is fine
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=${PORT:8080}

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Added to ensure your Java 'createdAt' becomes 'created_at' in Postgres
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.session.jdbc.initialize-schema=${SPRING_SESSION_JDBC_INITIALIZE_SCHEMA:always}